### ISSUE TITLE
Support for newer versions of Terraform

### ISSUE THREAD

**Issue by danielhartnell** [nubisproject/nubis-terraform#37]
The WebOps team has encountered several different errors with Terraform. Since we've expanded our use to a number of members on the team, each of us has received varying error messages. Sometimes they are resolved by repeating the command. Sometimes the errors simply stop appearing. As an example, my coworker was able to get Terraform to crash once (new to me) after running Terraform apply.

I don't think this is necessarily a Nubis problem. I'm more interested in creating a feature request to ask that we support versions of Terraform newer than v0.6.16, which may include bug fixes. If you'd prefer, we can close this out and I can just work through specific errors that we're encountering in #nubis-users.

I don't have a specific error message to discuss right now.

**Comment by gozer** [comment]
Support for Terraform 0.8 is planned and work on it is already on its way, so stay tuned!

**Comment by danielhartnell** [comment]
Thanks, @gozer. Since this is on the roadmap, I'm going to go ahead and mark this as closed.
