### ISSUE TITLE
Create static_website module

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-terraform#44]
This module will create a cloudfront distribution and an s3 bucket associated with it

**Comment by gozer** [comment]
Wouldn't it make sense to first make a cloud front module, then stitch it with the existing bucket module to make this final static site module?

Just a 0.02$ thought

**Comment by limed** [comment]
While probably a good idea, at its current state the way the current modules (s3 in particular) work I believe there needs to be refactoring to get it to work with cloudfront. For now I wrote a module that just does s3 and cloudfront which we can split up later on

**Comment by limed** [comment]
I believe @gozer created a different way of doing this
